name: Build Mac App
on: [push]

jobs:
  build:
    runs-on: macos-latest
    steps:
      - name: Check out code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'
          architecture: 'arm64' # We stay on the modern runner but tell it to build for both

      - name: Install dependencies
        run: |
          pip install pyinstaller yt-dlp Pillow

      - name: Build Universal Mac App
        run: |
          pyinstaller --noconsole --onedir --windowed \
          --target-architecture universal2 \
          --add-data "staffordsongs.db:." \
          --add-data "Rare Soul Playlists.png:." \
          Torchlight_v43.py

      - name: Upload Executable
        uses: actions/upload-artifact@v4
        with:
          name: Torchlight-Mac-App
          path: dist/Torchlight_v43.app
