name: Build Mac Apps (Intel & Apple Silicon)
on: [push]

jobs:
  build:
    strategy:
      matrix:
        include:
          # Change macos-13 to macos-15-intel
          - { arch: x86_64, runner: macos-15-intel, name: Intel-Mac }
          - { arch: arm64, runner: macos-latest, name: Apple-Silicon-Mac }
    runs-on: ${{ matrix.runner }}
    steps:
      - name: Check out code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          pip install pyinstaller yt-dlp Pillow

      - name: Build App
        run: |
          pyinstaller --noconsole --onedir --windowed \
          --add-data "staffordsongs.db:." \
          --add-data "Rare Soul Playlists.png:." \
          Torchlight_v43.py

      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: Torchlight-${{ matrix.name }}
          path: dist/Torchlight_v43.app
